---
apiVersion: v1
kind: Service
metadata:
  name: challenge
  labels:
    app: challenge
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 10000
      protocol: TCP
      name: http
  selector:
    app: challenge
